# Generated by Django 4.2.2 on 2023-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='allow_dates',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
