# Generated by Django 4.2.2 on 2023-06-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('products', '0002_alter_productimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='tag', to='tags.tag'),
        ),
    ]
